apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-west-2c
      containers:
      - name: mysql
        image: mysql:8.0.30  
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          # # Replication Configuration
          # - name: MYSQL_REPLICATION_MODE
          #   value: "master"  # Specify whether this pod is a master or a replica
          # - name: MYSQL_MASTER_HOST
          #   value: "master-hostname"  # Replace with the actual master hostname
          # - name: MYSQL_MASTER_PORT
          #   value: "3306"  # Replace with the actual master port
          # - name: MYSQL_MASTER_USER
          #   value: "replication_user"  # Replace with the actual replication user
          # - name: MYSQL_MASTER_PASSWORD
          #   value: "replication_password"  # Replace with the actual replication password
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: mysql-gp2
        resources:
          requests:
            storage: 1Gi
