apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  labels:
    app: mariadb
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb-headless"
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      # # 1) One pod per node
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: app
      #               operator: In
      #               values: ["mariadb"]
      #         topologyKey: "kubernetes.io/hostname"
      # 2) Try to balance across zones
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: "topology.kubernetes.io/zone"
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: mariadb
      containers:
        - name: mariadb
          image: mariadb:10.6
          ports:
            - containerPort: 3306
              name: mariadb
          envFrom:
            - secretRef:
                name: mariadb-secret
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
            - name: mariadb-config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mariadb-config-volume
          configMap:
            name: mariadb-config
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi
